# Generated by Django 3.1.5 on 2021-02-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('discription', models.TextField(blank=True, max_length=500)),
                ('team_size_mn', models.IntegerField(default=1)),
                ('team_size_mx', models.IntegerField(default=4)),
            ],
        ),
    ]
