# Generated by Django 3.1.5 on 2021-02-01 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('team_size', models.IntegerField(default=1)),
                ('team_id', models.CharField(max_length=100, null=True)),
                ('team_active', models.BooleanField(default=False)),
                ('team_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('team_member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('team_not_accepted', models.ManyToManyField(related_name='pending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
